# Generated by Django 3.1.4 on 2021-01-29 10:23

import apps.article_image.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0004_auto_20210129_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.article_image.models.user_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_image', to='article.article')),
            ],
        ),
    ]
