# Generated by Django 3.1.4 on 2021-02-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_category', '0002_remove_articlecategory_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
