# https://docs.docker.com/compose/compose-file/

version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-14-november-2020/final-projects/taxjungle/taxjungle:latest
    restart: always
    command: 'sh /scripts/dev.sh'
    env_file:
      - ./envs/dev.env
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend
      - static-files:/static-files
      - media-files:/media-files
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - ./envs/dev.env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  static-files:
  media-files: