name: taxjungle_backend
dependencies:
  - python=3.9.1
  - psycopg2
  - pip
  - pip:
      - coreapi==2.3.3
      - django==3.1.4
      - djangorestframework==3.12.2
      - djangorestframework-simplejwt==4.6.0
      - drf-yasg==1.20.0
      - markdown==3.3.3
      - pillow==8.0.1
      - gunicorn==20.0.4
      - flake8==3.8.4
      - django-cors-headers==3.6.0