# Generated by Django 3.1.4 on 2021-01-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_auto_20210128_1401'),
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='social_networks',
        ),
        migrations.AddField(
            model_name='share',
            name='social_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share', to='social_network.socialnetwork'),
        ),
    ]
