# Generated by Django 3.1.4 on 2021-01-28 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shared_by',
            field=models.ManyToManyField(blank=True, related_name='share_article', to=settings.AUTH_USER_MODEL, verbose_name='shared_by'),
        ),
    ]
