# Generated by Django 3.1.4 on 2021-01-29 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_category', '0002_remove_articlecategory_article_category'),
        ('article', '0005_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_category', to='article_category.articlecategory'),
        ),
    ]
