# Generated by Django 3.1.4 on 2021-02-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_category', '0003_auto_20210203_1318'),
        ('article', '0007_auto_20210201_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='article_category.articlecategory'),
        ),
    ]
