# Generated by Django 3.1.4 on 2021-02-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20210208_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
