# Generated by Django 3.1.4 on 2021-01-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='email',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='social_network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
